image: Ubuntu
platform: x64
stack: node lts/*
skip_tags: true

install:
  - npm install

build_script:
  - npm run build

test_script:
  - npx codecov

artifacts:
  - path: bundle/bundle.zip
    name: ${APPVEYOR_BUILD_VERSION}

deploy:
  release: ${APPVEYOR_BUILD_VERSION}
  description: '${APPVEYOR_BUILD_VERSION}'
  provider: GitHub
  auth_token:
    secure: LZivqelZnFmrHH+iuzgusfnKcf0TpgR9aa4JAhkfD4M4i1+1ABtPnUAL2CtlpzCT
  draft: false
  prerelease: false
  on:
    branch: master