image: Ubuntu
platform: x64
stack: node lts/*
skip_tags: true

install:
  - npm install

build_script:
  - npm run build

test_script:
  - curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import > /dev/null
  - curl -Os https://uploader.codecov.io/latest/linux/codecov > /dev/null
  - curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM > /dev/null
  - curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig > /dev/null
  - gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
  - shasum -a 256 -c codecov.SHA256SUM
  - chmod +x codecov
  - ./codecov --disable=gcov

artifacts:
  - path: bundle/bundle.zip
    name: ${APPVEYOR_BUILD_VERSION}

deploy:
  release: ${APPVEYOR_BUILD_VERSION}
  description: '${APPVEYOR_BUILD_VERSION}'
  provider: GitHub
  auth_token:
    secure: LZivqelZnFmrHH+iuzgusfnKcf0TpgR9aa4JAhkfD4M4i1+1ABtPnUAL2CtlpzCT
  draft: false
  prerelease: false
  on:
    branch: master
